### ISSUE TITLE
Code commited as binary format

### ISSUE THREAD

**Issue by sentryjs** [roexian/homeBrew#1]
Cannot read code on github or after cloning.
![image](https://cloud.githubusercontent.com/assets/761009/6907042/7f2b0928-d6f8-11e4-9c1b-599a1c8a7efa.png)
![image](https://cloud.githubusercontent.com/assets/761009/6907058/a0d2d646-d6f8-11e4-9ebd-e558847df581.png)

**Comment by roexian** [comment]
Accidentally sync'd shortcuts
